### ISSUE TITLE
Candidates doesn't contain all candidates

### ISSUE THREAD

**Issue by Neutrinoant** [pvigier/fractal-image-compression#3]
Hi, i'm learning FIC and find an important error from your codes.
Rotating and flipping domain blocks makes 8 different blocks but 'zip' function doesn't do this correctly. The function zip allows lists(or something) which sizes all equal and concatenate element-wise.
`candidates = list(zip(directions, angles))`
I found that code makes only 2 candidates (1,0) and (-1,90). It can be corrected using 'itertools.product':
`candidates = list(itertools.product(directions, angles))`
It will increase the performance i think :)

**Comment by pvigier** [comment]
Oh yes, you're right. Nice catch!

Do you want to do the PR?

By the way, you can also achieve a cartesian product in Python like this:

```python
candidates = [[direction, angle] for direction in directions for angle in angles]
```

**Comment by Neutrinoant** [comment]
Yeah it needs no additional library, good!
I want to do PR using that code. It took some time to me to understand that procedure since i'm almost new to git branching system. haha now i'm done

**Comment by pvigier** [comment]
Haha first time is hard but you did well.

Have a nice day (or night)!
