### ISSUE TITLE
Please add a "LICENSE" file

### ISSUE THREAD

**Issue by shlomif** [pvigier/fractal-image-compression#5]
Hi!

See https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#i-want-to-release-my-code---which-open-source-licence-should-i-use .

Thanks!

**Comment by pvigier** [comment]
Hi!

Fixed by 0a075ae.

Thanks!

**Comment by shlomif** [comment]
Great! Thanks,  that was quick.
