### ISSUE TITLE
How do you ensure contraction without bounded variable least squares?

### ISSUE THREAD

**Issue by pijatizu** [pvigier/fractal-image-compression#7]
Hi, I've been reading up on fractal compression and I love that this repo gives a concise, understandable, usable implementation of it. One issue -- it looks like your least squares function allows solutions with `|contrast|` much greater than 1. This means non-contractive mappings will be admitted, no? How do you avoid explosion in decompression?

**Comment by pvigier** [comment]
Hi, if I remember correctly, `contrast` can be between `-factor` and `factor` and the whole transformation is still a contraction thanks to the reduction that is applied before. I once made the calculation of the bound but I am afraid I lost the paper a long time ago so I may be wrong.

Currently, there is nothing that ensures this condition. I think I tried to achieve this with this line: https://github.com/pvigier/fractal-image-compression/blob/5d3a12fbd5ebe94a93c827ba6a87d382eeeebf68/compression.py#L52

I have no idea why it is commented and I preferred the non-constrained version, maybe it is faster. 

Sorry, I can't help you more.
