### ISSUE TITLE
Dimensions of decompressed fractal 

### ISSUE THREAD

**Issue by sendeniz** [pvigier/fractal-image-compression#8]
Hi pvifiger, 
first of all, very nice work. Thank you for making this available to everyone. 
I was curious about the following, shouldn't the decompressed fractal have the same dimensions as the original input image ? 
From what I could tell the dimensions of the original image and the fractal decompressed image do not match. Any idea why this could be ?

**Comment by pvigier** [comment]
Hi, yes in the example, the size of the input image is reduced to make the computations a lot faster with this line :
https://github.com/pvigier/fractal-image-compression/blob/5d3a12fbd5ebe94a93c827ba6a87d382eeeebf68/compression.py#L164

**Comment by sendeniz** [comment]
> Hi, yes in the example, the size of the input image is reduced to make the computations a lot faster with this line :
> 
> https://github.com/pvigier/fractal-image-compression/blob/5d3a12fbd5ebe94a93c827ba6a87d382eeeebf68/compression.py#L164

Ok, this is understandable as computation is quite costly. Thank you for this Pviger. 
Would I be able to ask you an additional questions ? Given an image size of i.e., 64 * 64 is it possible to obtain an fractal compressed image of the same size or is the fractal compressed image always smaller than the original? 

I am primarily wondering about this, because of a metric where the RMSE(original_image, fractal_compressed_image) is being computed. If the compressed image always has a dimensionality smaller than the original, this would mean that they are infact not using the fractal compressed image, but the fractal decompressed image. 

Please let me know about this Pviger
And thank you sharing your software again.

**Comment by pvigier** [comment]
After compression, there is no image, only a transform whose fixed point is near the input image. Maybe, you mean the uncompressed image? The uncompressed image has the same size as the input image.

If the reduction of size in the examples perturbs you, you can just erase the line, it will work with the original image size.

With a 64x64 image size, it should be relatively fast so you don't need to reduce the size.
